### ISSUE TITLE
how to view debug prints (win32)

### ISSUE THREAD

**Issue by ChristianHohlfeld** [networkprotocol/yojimbo#100]
How can configure yojimbo so I can see the debug logs in visual studio for win32 (not console application) ?

A forum would be nice so questions could be answered otherwise.
Thank you all.
Cheers,
Chris.

**Comment by gafferongames** [comment]
I don't know, does anybody?

**Comment by ChristianHohlfeld** [comment]
You can close this issue, I found a solution described in this article: http://dslweb.nwnexus.com/~ast/dload/guicon.htm
The program allocates a new console window and redirects the io to it.
 If for whatever reason you can't see any messages printed to the console window you can use this fix: https://stackoverflow.com/questions/15543571/allocconsole-not-displaying-cout
