### ISSUE TITLE
Fix valgrind reported errors

### ISSUE THREAD

**Issue by drichardson** [networkprotocol/yojimbo#114]
In PR #112, valgrind reported some non-leak errors. As I mentioned in that PR, it isn't clear if this is a regression or even an actual bug. Need to investigate.

**Comment by drichardson** [comment]
@gafferongames You can assign to me if you like. I just wanted a place to keep track of it since I don't plan to investigate immediately.

**Comment by gafferongames** [comment]
Cool thanks!

**Comment by drichardson** [comment]
Actually, I probably won't get to this. I thought we were going to use Yojimbo but at this point we are not. Probably should unassign me.

**Comment by gafferongames** [comment]
OK no worries!
