### ISSUE TITLE
Reliable Ordered messages only send 1024 bytes per call to SendPackets

### ISSUE THREAD

**Issue by TrianglesPCT** [networkprotocol/yojimbo#118]
I was trying to send map data when a player first connects, this is a fairly large, at least a few MB.

It was taking *forever*, looking at the code I can see that yojimbo only sends 1 fragment of the block per call to SendPackets(), and since blockFragmentSize is 1024 bytes, well that means it only sends 1024 bytes per tick.

I "fixed" by doing this

	for (int i = 0; i < 100; ++i) {
		serv->SendPackets();
	}

I'm not seeing any variables to make it send more than 1 fragment per call to SendPackets.
Is this intended behavior? 
Would adding a variable to the channel to indicate how many fragments it can send per Tick be acceptable?
Or should I just make that channels blockFragmentSize huge?

**Comment by gafferongames** [comment]
As designed.
