### ISSUE TITLE
Loopback memory leak

### ISSUE THREAD

**Issue by Green-Sky** [networkprotocol/yojimbo#119]
Hi, I'm getting a memory leak error when connecting a Client through Loopback.
The fix seems to be calling `server.DisconnectLoopbackClient(clientIndex)` before `server.Stop()`.
You don't do this in the loopback.cpp example and the example is not leaking anything, so there might be an error on my side.

**Comment by gafferongames** [comment]
Can you please get us a repro that demonstrates this error. Thanks!

**Comment by gafferongames** [comment]
If you can create a repro in test.cpp that clearly demonstrates this error, I'm happy to look into it. Until then, closing this issue.
