### ISSUE TITLE
Linking and starting the server

### ISSUE THREAD

**Issue by le-water** [networkprotocol/yojimbo#123]
I have a couple questions:

1. How do i link the server with my game?

2. How do i start the server ( is there a start.bat or something?) ?

3. Is there a way to link this with companies such as playfab or gamesparks?

4. Can i manage the server with cloudly? ( https://github.com/janfilips/cloudly )

5. Is there a way to put an anti-cheat on the server?

I am sorry about the questions, but I’m in charge of the servers for our game and I’ve absolutely never worked with servers before. I hope you don’t mind the questions.

**Comment by garettbass** [comment]
This document may be helpful to you:

https://github.com/networkprotocol/yojimbo/blob/master/USAGE.md
