### ISSUE TITLE
Precompiled external libraries and x86 support

### ISSUE THREAD

**Issue by Karmel0x** [networkprotocol/yojimbo#134]
1. Why use precompiled external libraries https://github.com/networkprotocol/yojimbo/tree/master/windows instead of submodules / requiring self-build ?
It disallowing to build to other architecture.
https://github.com/jedisct1/libsodium
https://github.com/ARMmbed/mbedtls

2. Something is crashing in secure_client compiled for Win32.

3. Why don't use netcode.io and reliable.io as library ?

**Comment by gafferongames** [comment]
Go away

**Comment by EkajArmstro** [comment]
Does this mean yojimbo explicitly doesn't support 32 bit windows? I got it to compile by building libsodium and mbedtls (without explicit crypto and x509 .lib files) and by changing the size of netcode_socket_handle_t. Are there known issues, or is it just not tested?

**Comment by gafferongames** [comment]
It should work fine, just build from source. If you have a repro for issues on Win32, I'm sure they are easy to fix and I'm happy to accept a PR.

**Comment by EkajArmstro** [comment]
Thanks!
