### ISSUE TITLE
Not ideal for MMOs?

### ISSUE THREAD

**Issue by Mmpuskas** [networkprotocol/yojimbo#135]
I saw mention [here](https://forums.inovaestudios.com/t/what-is-your-favorite-networking-library/4695/2) and [here](https://github.com/networkprotocol/yojimbo/issues/57#issuecomment-311389186) about using other libs (potentially raknet/slikenet) for something like an MMO, but I couldn't find much beyond that. Mind giving a quick explanation of why?

Thanks.

**Comment by gafferongames** [comment]
MMOs have lots of players. Generally, you need to spend a lot of time optimizing your socket layer to support many simultaneous connections. I've already done that for this library, and it's reasonable up to 256 simultaneous connections, but beyond that I make no guarantees, and I think you'll need to optimize parts of the library.

So, in short, you're welcome to try to use it. I think there's probably places where you'll want to optimize away O(n) walks across session arrays. But aside from that, netcode is as good as any library for an MMO.

cheers

- Glenn

**Comment by Mmpuskas** [comment]
Thanks for the elaboration!
