### ISSUE TITLE
A simple example for a beginner

### ISSUE THREAD

**Issue by kireita** [networkprotocol/yojimbo#136]
Hello.

Where can i find an example of:

- a client sending a message to the server
- a server sending a broadcast to the clients

i want to understand how to simply ping a server or send a "Hello world" to anyone that is connected.

thank you in advance.

**Comment by Green-Sky** [comment]
I'm not sure you are aware, but there is the [USAGE.md](https://github.com/networkprotocol/yojimbo/blob/master/USAGE.md) file, which goes through the basic usage of the library.

**Comment by kireita** [comment]
thank you!, i indeed didnt knew... sorry for my ignorance!
