### ISSUE TITLE
Matcher in C++?

### ISSUE THREAD

**Issue by erwincoumans** [networkprotocol/yojimbo#140]
Thanks for sharing the project Glenn!

Just curious: why is the matcher written in Go? Is there a C++ version somewhere?

Also, does the library support secure transfer of password over the network and storage of hashed (salted) password locally?

**Comment by gafferongames** [comment]
Just in golang because it's faster to code web services in that language. Yes, transfer is secure (encrypted and signed). I don't have support for salted passwords locally, but use a token system. Crypto behind my library is: https://github.com/jedisct1/libsodium and it probably supports what you need.

**Comment by erwincoumans** [comment]
Thanks for the quick reply. Can you share a few words why do we need web services in the first place?

The C++ server could have a matchmaker lobby integrated, or would that introduce attack opportunities?

**Comment by gafferongames** [comment]
The security model for netcode (and yojimbo, which uses netcode) requires that you have your own backend where you can generate a token. This token is used for client -> server connection authentication, basically ensuring that only clients that received a token from your backend can connect to your server.

It doesn't matter what language your backend is written in, but you do need one. Having a system where clients can connect directly to a server hosted somewhere is just asking for zombie clients and DDoS....

**Comment by gafferongames** [comment]
So the flow is, your client requests a match from your backend (matcher is standing in for this in examples).

Matcher gives a token to your client.

Client takes that token and uses it to connect to the server (it is self contained).

Server verifies token is cryptographically valid, eg. was generated by your backend with your private key.

Server should not be in the hands of your customers. The server should be run on a dedicated secure server somewhere, controlled by you.

cheers
