### ISSUE TITLE
Several warnings about missing sodium.pdb

### ISSUE THREAD

**Issue by sfla** [networkprotocol/yojimbo#145]
By simply building Yojimbo.sln I get a ton of warnings LNK4099 saying that sodium.pdb is missing. A quick web search says that it's a file related to debugging, and most forums say to "just rebuild sodium and copy its .pdb-file". 
Well, how? First of all, I can't find it. I find something called "libsodium", but compiling that just gives me a libsodium.pdb, not a sodium.pdb.
Since it's just added to the repo as a dll and headerfiles instead of a submodule, I don't know how to find the real source so I can rebuild it.
I'm a complete noob, so I have no idea what to do about it. Having debugging capabilities in sodium isn't that important, but that output is really fucking annoying.

And I also get a warning saying "LNK4098 defaultlib 'MSVCRT' conflicts with use of other libs; use /NODEFAULTLIB:library", which I don't understand how that can be happening when I'm literally just running an unedited Yojimbo.sln. Don't know if it's related.
Btw, using Visual Studio 2019.

**Comment by gafferongames** [comment]
To solve this build and link sodium from source.
