### ISSUE TITLE
Question - NAT Punch-through

### ISSUE THREAD

**Issue by onehundredfeet** [networkprotocol/yojimbo#159]
Hi,

I can't seem to find any NAT punch-through logic in Yojimbo. Is there a natural path to extending the matcher system to include nat-punch through to allow a host and client to see each other across a NAT?

Cheers,
Ryan.

**Comment by gafferongames** [comment]
Not supported. Yojimbo is for client/server games where the server has a public IP address.

**Comment by eidetic-av** [comment]
@onehundredfeet for anyone thinking of this, it may be possible to use this library in conjunction with a STUN server to determine the external IP required for communication behind a NAT.

**Comment by lolirelia** [comment]
@gafferongames I imagine it's still sufficient for P2P if both players are able to traverse NAT through other means?

**Comment by gafferongames** [comment]
Potentially, but unsupported.
