### ISSUE TITLE
Several Issues / Questions

### ISSUE THREAD

**Issue by Spooks4576** [networkprotocol/yojimbo#160]
Hi there, I recently started using your network library and I am having some trouble getting things working.
I Followed the exact steps in USAGE.md, and it brought me to a basic understanding as to how to use the library. 
Sadly I am running into a couple issues. when it comes to following the examples in server.cpp. and client.cpp. 

First issue or bug I wanted to bring to your attention. is the Send Message Function at least for me is getting redefined in WinUser.h.
I use this library to get key presses. and other useful things. but for whatever reason it seems to override the Function Send Message in both server and client. so if you know another way to fix this please lemme know. 

Second Issue I am having is getting references to both Client and Server Classes. no matter if I inherit those classes in another class. passing a pointer to another function seems to be rather difficult. considering it always says that a default constructor for said class is not accessible. when trying to make a new instance of said class, or when trying to make a pointer to it. so I guess my question for this issue is. how would I go about defining these Classes globally so its not just a local variable, since global variables give me the constructor error and I would like to access these Classes Globally

Lastly When trying out the examples from client.cpp and Server.cpp I try to send a message on a key press in the while loop or game loop where the packets get sent and received unfortunately during my tests Sending a Message seems to completely stop the while loop from executing again Therefor causing the server to disconnect the client due to timeout I have no idea if this is a logic issue or a bug on your end but I just wanted to let you know 

Anyway I hope you can get back to me soon I have been struggling with this for weeks 
Thank you for such a Amazing Network Library :)

**Comment by Spooks4576** [comment]
Fixed the issues on my own Turns out Time Was not being defined properly for the second issue as for the last issue its fixed as well first issue seems to be a bug i can just if def it so im closing this

**Comment by Tectors** [comment]
Yes, I agree as I am having the same problem.
