### ISSUE TITLE
Intended use of client messages

### ISSUE THREAD

**Issue by kingoftheconnors** [networkprotocol/yojimbo#178]
I'm somewhat confused by the USAGE example. It perfectly describes how messages are sent, but I'm lost on what best-practices are for using the library.

My naive implementation is to make each client authoritative over itself, but as mentioned in [GafferOnGames Article](https://www.gafferongames.com/post/what_every_programmer_needs_to_know_about_game_networking/), that's bad form.

So what IS encouraged form for a client-server game? What paradigm is Yojimbo made for?

**Comment by gafferongames** [comment]
Yojimbo is the answer to the question, what would the correct network stack for Apex Legends be?

**Comment by gafferongames** [comment]
Client -> server messages should be control messages. Not stuff like 'I fired my gun' ;)

**Comment by kingoftheconnors** [comment]
@gafferongames Thank you for responding! I've been reading your articles, and that confirms what I saw in your tutorial on [Deterministic Lockstep](https://gafferongames.com/post/deterministic_lockstep/). Does Yojimbo have a _Playout Delay Buffer_ internally, or do I have to put that together myself?

**Comment by gafferongames** [comment]
Yojimbo is just a library for you to define channels for communication, serialization for messages etc. It doesn't force you to any particular network model, although it has been designed with the needs of AAA games. You need to implement a playout delay buffer yourself.

**Comment by kingoftheconnors** [comment]
Awesome. Thank you so much!
