### ISSUE TITLE
Sending Large Block Sizes slow

### ISSUE THREAD

**Issue by tvanlenten** [networkprotocol/yojimbo#192]
Hello Glenn! Great library so far but I ran into trouble sending large amounts of data on a reliable ordered channel with block messages. I need to send a few MB of data initially and I am not really sure how to approach this. It took over 30 seconds on LAN to send only a few MB! Also apologies for opening an issue have no idea where else to ask this. Any hints in the right direction would be greatly appreciated! 

Thanks!

**Comment by gafferongames** [comment]
Just change the configuration of the channel to have larger packet sizes, and a larger slice size. This will get the data sent down faster. -- cheers
