### ISSUE TITLE
Understanding reliable ordered messages

### ISSUE THREAD

**Issue by nvisionGeo** [networkprotocol/yojimbo#55]
Hello Glenn! Thanks for the killer libraries. Just updated to your latest commit. Cleaned up so nicely.

I've been implementing a Unity plugin with yojimbo. Works really well overall. My biggest hangup is understanding how to tune the ordered reliable channel. For example, with unordered I can get a smooth 90 msgs per sec (256 bytes). With ordered, I am seeing a limit of 8 msgs per second for a 120ms server and about 60 msgs per second on LAN. To get the fastest rate I had to tweak the main loop Hz, min resend time and send rate.  I've read your articles before starting. Maybe I will re-read them. Otherwise, any hints would be greatly appreciated!

Geo

**Comment by gafferongames** [comment]
First, let's start with what you are trying to achieve?

**Comment by gafferongames** [comment]
And are you using the most recent version of yojimbo (the latest source), or the last release? They are quite different.

**Comment by gafferongames** [comment]
Hey nvision, I see you are on the latest version. My guess is that the default config for the reliable-ordered channel needs to be relaxed a bit. I'll do some work on this over the weekend. Stay tuned.

**Comment by nvisionGeo** [comment]
Thanks! Looking forward to hearing back.

**Comment by gafferongames** [comment]
Sorry, I'm delayed on this, but it is still on my list of TODO. Stay tuned this week.

**Comment by nvisionGeo** [comment]
No worries, thank you. After re-reading the docs, I learned that reliable ordered messages are one-in-flight at a time. That probably explains the behavior I am seeing. I'm wondering if relaxing the default channel config will allow more than one-in-flight at a time.

**Comment by gafferongames** [comment]
Reliable-ordered messages are only one in-flight at a time when they are large messages with data blocks attached. Regular messages without blocks attached can have multiple in flight,
and included per-packet, according to the max # of messages per-packet in the channel config and the packet packet budget.

**Comment by nvisionGeo** [comment]
Thanks, I will do some testing with this info.

**Comment by gafferongames** [comment]
Sync up to latest master, I just added code to significantly relax the default reliable-ordered channel. Specifically, packet budget has been relaxed to allow it to fill the entire packet (was 1100 bytes or so), and a maximum of 256 reliable-ordered messages per-packet is now allowed (was 64).

This should significantly improve your reliable-ordered message throughput.

If it doesn't, please let me know.

For more info, see yojimbo_config.h and look at ChannelConfig in there

**Comment by gafferongames** [comment]
As to how reliable-ordered messages actually work, each message is repeatedly sent (while there is room in the packet), no faster than 10 times per-second, until a packet it is included in is acked. That's it. That's how they work :)

**Comment by gafferongames** [comment]
Closing this. Please comment if you are still having problems with the reliable channel with latest master.
