### ISSUE TITLE
Premake for Windows

### ISSUE THREAD

**Issue by hectorllanosSBM** [networkprotocol/yojimbo#59]
I wanted to use the build guildlines outlined in BUILDING.md, but I am unable to create the .sln file from premake. (I maybe doing it wrong)

I installed premake and pulled the latest release (0.6).
Opened up CMD and cd to yojimbo.
Then I typed 'premake5 solution'.

When it runs, I get an error that states: "Windows cannot find 'Yojimbo.sln'. Make sure you typed the name correctly, and then try again."

Am I suppose to make a .sln first? I am using VS 2015 and/or 2017

**Comment by gafferongames** [comment]
Please past the output from "premake5 solution" as well as the output from "premake5 --version"

cheers

- Glenn

**Comment by hectorllanosSBM** [comment]
C:\Users\Hector>premake5 --version
premake5 (Premake Build Script Generator) 5.0.0-alpha11

C:\Users\Hector\Desktop\yojimbo-0.6.0>premake5 solution
Running action 'solution'...
'premake5' is not recognized as an internal or external command,
operable program or batch file.
The system cannot find the file Yojimbo.sln.

**Comment by gafferongames** [comment]
You need to put the premake5.exe in your path, then it will work. Alternatively, just copy it into the yojimbo directory.

cheers
