### ISSUE TITLE
Building for Android

### ISSUE THREAD

**Issue by Alex-G** [networkprotocol/yojimbo#60]
Hey Glenn,
how to build yojimbo for Android on Windows?

Alex

**Comment by gafferongames** [comment]
I don't know?

**Comment by RickLamb** [comment]
I recently tried and failed on windows, can't remember the details. Ended up installing dualboot Linux, after that it was super smooth. You could try a VM if you're feeling lucky.

**Comment by Alex-G** [comment]
Hey Rick,
thanks for the tip, can you provide some details on how do you accomplish that,
and may send me your compiled lib so I can test my UE4 integration on Android quickly.

Thanks in advance!
Alex

**Comment by RickLamb** [comment]
Was part of a paid contract, so can't just give you the libs really.

libsodium:
from root of repo
export ANDROID_NDK_HOME=/blah/blah/Sdk/ndk-bundle
./dist-build/android-armv7-a.sh

mbedtls:
 just use cmake to generate make files with android toolchain - e.g. https://github.com/taka-no-me/android-cmake/blob/master/android.toolchain.cmake

**Comment by gafferongames** [comment]
Nice one RickLamb, appreciate the help.

**Comment by MattFoley** [comment]
Has anyone written up a comprehensive explanation of how to get this running on Android? I'm currently looking to compile this on both iOS and Android from OSX, but running into a lot of issues with Android due to needing libsodium  and mbedtls compiled for Android as well.

**Comment by gafferongames** [comment]
When you get it working, I am happy to accept pull requests. -- cheers
