### ISSUE TITLE
https://github.com/networkprotocol/netcode.io/tree/7b405ab738ce07f224bdfab2bc48b024f9d17f13 doesn't seem to exist

### ISSUE THREAD

**Issue by IRog** [networkprotocol/yojimbo#61]
I can't get the submodules for the project, as the version specified for netcode.io isn't valid (https://github.com/networkprotocol/netcode.io/tree/7b405ab738ce07f224bdfab2bc48b024f9d17f13).

Also thanks for this library. I look forward to playing around with it...

**Comment by gafferongames** [comment]
Yes, sorry I am working on fixing this right now.

**Comment by gafferongames** [comment]
Please grab the 1.0 release zip fro the moment: https://github.com/networkprotocol/yojimbo/releases/tag/v1.0

**Comment by IRog** [comment]
Thanks for the quick response!

**Comment by gafferongames** [comment]
This should be resolved now.
