### ISSUE TITLE
Connect vs InsecureConnect

### ISSUE THREAD

**Issue by maxw** [networkprotocol/yojimbo#65]
Heyo,

I just wanted to check that the only difference between the secure_client/secure_server and the regular client/server examples is the token from the matcher.

I'm using yojimbo for a game where the sessions can be quite long in duration (possibly days). I have an accounts service that generates a session token (instead of a matcher instance). The user then connects to a yojimbo instance via client.InsecureConnect() and gives the server its session token (which is then used to verify if that user can join this match). I do this because the session token needs to be continually evaluated to make sure it's valid throughout the duration of the session. (Someone can get banned mid-game)

Is this still going to be secure? As you can imagine calling client.InsecureConnect scares me a little. I assume data is still being encrypted with libsodium.

Max

**Comment by gafferongames** [comment]
In older versions of yojimbo, it was a different codepath for client connection without encryption. In the latest version, it is secure and uses identical codepaths to the secure connect, just that it requires some external mechanism to synchronize the encryption keys between client and server.

Seems like I should rename it back to "Connect"

**Comment by maxw** [comment]
Oh good point. I hadn't considered the DDoS route. I'll aim to integrate the matcher into our system then. Thanks for the info!

**Comment by gafferongames** [comment]
Yes, the key thing is that all you need to do is generate the connect token from your system, without the client knowing the private key. This private key must be known only to your web backend, and the dedicated server instances.

cheers

**Comment by maxw** [comment]
That makes sense. Thanks again!
