### ISSUE TITLE
Running in docker with mismatching ports

### ISSUE THREAD

**Issue by yamashi** [networkprotocol/yojimbo#66]
Hello,

I am trying to run a simple server in a docker instance, mapping the same port in the host machine as the container's binding port works like a charm.
docker run -it -p 10578:10578/udp is perfect.
As soon as I try to run 
docker run -it -p 10579:10578/udp it won't work anymore.

It is something I require to run multiple containers on the same machine, is there something in yojimbo that might be causing this behavior ?

Thanks,
Max

**Comment by gafferongames** [comment]
Can't think of anything!

**Comment by gafferongames** [comment]
Hmmm. Are you connecting through the matcher? You should implement something where the server advertises itself to the matcher via its *external* address, not the docker internal address, otherwise the connect tokens will not work, because they're setup on the internal port.

**Comment by gafferongames** [comment]
Test to see if the insecure connect works, if that works, but the connect token doesn't, then it could be that you are not properly reporting the external address to the matcher from your server.

**Comment by yamashi** [comment]
No we aren't using the matcher, we do a hard connect, so in this case I just try to connect to 127.0.0.1:10579 and it doesn't appear to respond at all.

**Comment by gafferongames** [comment]
Which codepath are you connecting via, InsecureConnect or Connect?

**Comment by gafferongames** [comment]
ps. yojimbo_log_level( YOJIMBO_LOG_LEVEL_DEBUG ) on the client and server and copy the output from both here please. Should be easy to see what is going on there.

My guess is that the connect token is being discarded because it's not in the whitelist. eg. you need the docker instance to know what it's external IP:port is, and to set that as its address, so it doesn't ignore the connect token because the server is not in the whitelist.

cheers

**Comment by yamashi** [comment]
InsecureConnect, managed to fix it by adding yojimbo::Address("0.0.0.0", 10578) to the serverAddresses in case someone runs into this issue!

Keep up the good work!

**Comment by gafferongames** [comment]
Sorted. Yeah, I noticed I had to bind to 0.0.0.0 as well earlier on while doing examples. Docker...

cheers

:)

**Comment by gafferongames** [comment]
OK that's a good workaround!
