### ISSUE TITLE
ignored connection request packet. connect token expired

### ISSUE THREAD

**Issue by yamashi** [networkprotocol/yojimbo#67]
Hi again,

A new problem arises, using InsecureConnect, with every server that is not hosted on my machine, the server will spam 
"ignored connection request packet. connect token expired"
when I try to connect to it, other people are managing to connect to the server.
Any idea what could be causing this ?

Client log:
`client sent connection request packet to server
client sent connection request packet to server
client sent connection request packet to server
client sent connection request packet to server
client sent connection request packet to server
client sent connection request packet to server
client sent connection request packet to server
client sent connection request packet to server
client sent connection request packet to server
client sent connection request packet to server
client sent connection request packet to server
client sent connection request packet to server
client sent connection request packet to server
client sent connection request packet to server
client sent connection request packet to server
client sent connection request packet to server
client sent connection request packet to server
client sent connection request packet to server
client sent connection request packet to server
client sent connection request packet to server
client sent connection request packet to server
client sent connection request packet to server
client sent connection request packet to server
client sent connection request packet to server
client sent connection request packet to server
client sent connection request packet to server
client sent connection request packet to server
client sent connection request packet to server
client sent connection request packet to server
client sent connection request packet to server
client sent connection request packet to server
client sent connection request packet to server
client sent connection request packet to server
client sent connection request packet to server
client sent connection request packet to server
client sent connection request packet to server
client sent connection request packet to server
client sent connection request packet to server
client sent connection request packet to server
client sent connection request packet to server
client sent connection request packet to server
client sent connection request packet to server
client sent connection request packet to server
client sent connection request packet to server
client sent connection request packet to server
client sent connection request packet to server
client sent connection request packet to server
client connect failed. connect token expired
client disconnected
client changed state from 'sending connection request' to 'connect token expired'`

Thanks,
Max

Edit: Added client log

**Comment by gafferongames** [comment]
I believe it is because the timestamp is out of sync with the server. Log the timestamp on your server vs. the timestamp on wherever you are generating the tokens. I would imagine that generating the tokens on machines (insecure connect) is going to be very problematic, unless they all have synchronized time.

Also, google the docker time drift thing on macosx. There is a bug where the VM drifts time from the local VM, you can fix it, for an example workaround, look in my premake5.lua for "alpine"

cheers

**Comment by yamashi** [comment]
Would it be unsafe if we were to remove the token expiration condition ? The matchmaker process doesn't integrate well with our current architecture :(

**Comment by gafferongames** [comment]
It's already unsafe if you are generating tokens on the client. This compromises the DDoS protection for dedicated servers, which is designed to only allow clients to connect who have authenticated through the matcher.

Any other use case is not really what yojimbo was intended for.

**Comment by gafferongames** [comment]
So I think, if you are already unsafe, why not be even more unsafe? :) Remove the address whitelist check, and the expire time. If tokens are generated on the client, you're already insecure, and you are no worse off by removing these things than you were before.
