### ISSUE TITLE
Custom socket

### ISSUE THREAD

**Issue by Scraft** [networkprotocol/yojimbo#68]
I was wondering what the feasibility is of being able to use a custom socket implementation, i.e. I am working on a restricted hardware platform where instead of normal sockets, there is a vendor provided socket implementation (different functions/params but very similar), which has the same properties of UDP (however I'd like to have reliable, ordered packets). Essentially, rather than passing in an address for yojimbo to open, I'd like to open the socket myself, and then pass yojimbo my socket (as a void* or whatever), and then register functions with yojimbo for sending, receiving and closing said socket.

What are your thoughts?

**Comment by gafferongames** [comment]
I think the easiest way for you to do this for the moment is to take the netcode.io implementation, and point it to your socket implementation. Yojimbo uses netcode.io for socket IO exclusively. Take a look, the code is pretty small. http://netcode.io

**Comment by gafferongames** [comment]
If you were to extend netcode.io to have support for swapping out the socket functionality, then you would be able to wrap that functionality with yojimbo and expose the interface you want.

Or, you could just wholesale modify yojimbo to use your socket implementation instead of mine.

cheers

- Glenn

**Comment by Scraft** [comment]
I started at netcode.io and it looked ideal, however it sounded like it supports guaranteed delivery but not order? Was that the case?

**Comment by gafferongames** [comment]
netcode.io is just the low level client/server connection layer and sockets. It is used by yojimbo, so if you want to change how the sockets work for yojimbo, look there.

cheers

**Comment by gafferongames** [comment]
I am currently adding support for overridden packet send and receive to netcode.io, because I have need for it in another project I'm working on. Take a look when I check it in, it will probably do what you need.

**Comment by Scraft** [comment]
Thank you; I did add a chunk of work towards replacing the sockets in netcode.io - but I was going to have to ask you some questions as to whether my approach was going to be acceptable to be integrated back - so if it is something you are now doing, that sounds good. I basically set up a struct with a bunch of callback functions in for things like open, close, bind, set_non_blocking, send, receive, etc. which can be set via a function, if they aren't set then it defaults the callbacks to pointing at the standard socket functions, otherwise it'll use the custom functions. The custom functions themselves had the exact same prototypes as the system socket functions, which doesn't map on 100% to the implementation I need to integrate, but my thoughts were that I'd just use a map/dictionary to map on things like address to my own structures relevent for the platform I am working on.

If you are a registered Switch developer, then to give you some idea, I was looking at using this to wrap VSockets.

**Comment by gafferongames** [comment]
Very nice! I did it a different way, they're probably not compatible, but I checked in my work last night. Take a look. The assumption is that you can have a "callback_context" that maps to the particular socket, and it just implements send and receive methods.

**Comment by Scraft** [comment]
From taking a look at the commit, I am currently not 100% sure how I could utilize this, i.e. netcode_client_create calls netcode_socket_create which sets ```s->handle = socket``` whereas I need to avoid making any calls directly from the socket library, and instead route all of these into custom methods. Perhaps I basically need to take what I've got so far, but remove my functions for send/receive (as you have already exposed that)? I could get what I have neatened up and shared on GitHub so you can take a look and tell me whether you feel something along these lines makes sense for the library.

**Comment by gafferongames** [comment]
You setup a config and set override_send_and_receive to 1 in that config. This stops the socket from getting created. Then it calls send_packet_override and receive_packet_override when it needs to do socket operations. It passes a void* callback_context, which is where you would store the socket and other data that you need for sending and receiving packets for that client or server.

**Comment by Scraft** [comment]
I maybe missing something, but I believe the code in netcode_server_receive_packets should be:
```while ( 1 )
{
	int packet_bytes;
	struct netcode_address_t from;
	uint8_t packet_data[NETCODE_MAX_PACKET_BYTES];

	if (server->config.override_send_and_receive)
	{
		packet_bytes = server->config.receive_packet_override(server->config.callback_context, &from, packet_data, NETCODE_MAX_PACKET_BYTES);
	}
	else
	{
		packet_bytes = netcode_socket_receive_packet(&server->socket, &from, packet_data, NETCODE_MAX_PACKET_BYTES);
	}
        /// ...
}
```
rather than the currently committed:
```while ( 1 )
{
    struct netcode_address_t from;
    uint8_t packet_data[NETCODE_MAX_PACKET_BYTES];
    int packet_bytes = netcode_socket_receive_packet( &server->socket, &from, packet_data, NETCODE_MAX_PACKET_BYTES );
    if ( packet_bytes == 0 )
        break;
    netcode_server_read_and_process_packet( server, &from, packet_data, packet_bytes, current_timestamp, allowed_packets );
}
```

As the currently comitted crashes when I call netcode_server_update when attempting to use the overrides you have kindly put in. Please let me know if I have overlooked anything.

**Comment by Scraft** [comment]
Similar for netcode_server_send_global_packet.

**Comment by Scraft** [comment]
Similar for netcode_server_send_client_packet.

**Comment by Scraft** [comment]
With those changes in place, it seems to work! I created a gist of my experiment here https://gist.github.com/Scraft/c4763e111aebfb24338cc01393c224f2 the net result was I was able to pass a message from client to server and server to client (please note my test is just assuming a single server/client running on the same machine - but of course if this works - it means I can replace the message queue with my real implementation).

**Comment by Scraft** [comment]
When I moved away from this test case, towards a proper implementation, where netcode.c isn't included into my modules source, I then got a compile error about netcode_address_t not being defined. To fix this, I moved this structure out of netcode.c and into netcode.h

**Comment by gafferongames** [comment]
Thanks for that. Sorry I must have missed those bits on the server. Derp. 

Yeah, I have to fix the address thing properly. I have a plan for that, stay tuned should be checked in shortly.

cheers
