### ISSUE TITLE
Sequence buffer out of order

### ISSUE THREAD

**Issue by larsolm** [networkprotocol/yojimbo#69]
We are having an occasional issue sending ordered messages. Most of the time everything works fine for an extended run, but sometimes we are hitting the assert in ReliableOrderedChannel::AddMessagePacketEntry.

We are sending reliable ordered messages fairly infrequently and the sequence number that gets passed to the Insert function seems to be getting incremented every time Server::SendPackets is called. We can reliably reproduce the assert by waiting ~32768 frames (i.e SendPacket calls) between sending a reliable ordered message.

It seems like the sequence passed to the sequence buffer should only increment when a message is sent rather than every frame, or else reliable messages need to be sent more often. Is this a bug or are we misusing something?

**Comment by gafferongames** [comment]
Yojimbo works under the assumption that you are sending packets in both directions continuously. Is this the case? Seems like it is. This could be a bug. Can you please create a test program that reproduces this and I can debug it for you.

cheers

- Glenn

**Comment by larsolm** [comment]
We are sending unreliable packets continuously in both directions and reliable messages only intermittently from server to client. The long period between sending reliable messages is what trigger's the assert.

After some investigation it looks like a new message will appear too old if it has been 32768 - 65536 runs through the game loop since the last time a message was sent. Test program coming shortly.

**Comment by larsoad** [comment]
Here is a test program based on the client_server.cpp example. I modified the example to send a continuous stream of unreliable messages from the client to the server and from the server to the client. After 32768 iterations the server will attempt to send a reliable message to the client, which will trigger the assert.

[client_server.zip](https://github.com/networkprotocol/yojimbo/files/1396737/client_server.zip)

**Comment by gafferongames** [comment]
Awesome. Thanks for the repro! I'll take a look tomorrow

**Comment by gafferongames** [comment]
Sorry for the delay, I'll have this sorted out this weekend for you.

**Comment by larsoad** [comment]
No problem, it happens rarely enough that it's not holding us back at all. Thanks for taking the time to look at it

**Comment by gafferongames** [comment]
Thanks. Sorry still slammed with work at my startup. Will get to this shortly.

**Comment by gafferongames** [comment]
Again, sorry for the delay. I'm working on a new startup now (http://networknext.com) so my time is limited. I will get to this.

**Comment by fire** [comment]
Friendly ping ❤️

**Comment by larsoad** [comment]
For others running in to this issue, you can work around it by making sure you send a reliable message from the server at least once every 32768 updates. In our case we couldn't guarantee that would always happen during normal gameplay so we added an empty message that gets sent and ignored by the clients every 60 seconds.

**Comment by gafferongames** [comment]
Yes, my guess is that I'll need to implement a similar solution, automatically, per-channel to resolve this. I've never had a test case where messages weren't sent. But the bug is real :)

**Comment by gafferongames** [comment]
Update on this one. So sorry, I'm so busy with my startup. The workaround suggested here is good. Please use this workaround, until I get time to apply that same workaround strategy internally.

cheers

**Comment by gafferongames** [comment]
We could use some help implementing this fix! Sorry I'm super slammed with my new startup!

**Comment by gafferongames** [comment]
I believe this is fixed with the latest yojimbo version (fix was to reliable.io). Please verify.
