### ISSUE TITLE
BlockMessage + Reliable Channel

### ISSUE THREAD

**Issue by maxw** [networkprotocol/yojimbo#71]
Heyo,

Apologies for using github issues to ask questions. For the most part I've been able to solve everything from looking at the source, but this one is a little trickier.

In short, does it make sense to send variable length reliable RPC messages using BlockMessage? I know you've previously mentioned that these messages are generally better for downloading a large chunk of data once (like downloading a level) because they only allow one to be in-flight at a time. So I assume the answer is "don't use BlockMessage" for this, but I figured I'd double check.

The longer version of the story is that I have an app that sends a large amount of reliable RPC messages (90-180/sec). Each RPC contains a small buffer of data that varies in size. Most of the time, these buffers are very small (20-40 bytes), however, occasionally we'll see a single message here and there that's larger than the WriteStream buffer (8 * 1024 according to the default connection config).

Architecturally, I'd love to just have a single message type that is a subclass of BlockMessage. However, it looks like I should probably make two subclasses. One that's a subclass of Message and one BlockMessage that I use whenever the buffer is larger than the WriteStream buffer size.

Anyway, I wasn't sure if Yojimbo makes an exception if the entire block message fits inside of a single packet.

Max

**Comment by gafferongames** [comment]
Yes, it would be a mistake, because block messages stall the send queue (only one block message may be in flight at any time).

What I would recommend instead is a message with a block of memory attached to it (you can even do this dynamically, look at stream.GetAllocator()), and then you write a serialize function that just serializes # of bytes, and the byte data.

Of course, this data needs to fit inside a single packet...

You could have two message types, one for large blocks and one for smaller messages. If they are reliable-ordered and sent on the same channel, they will still arrive in order.

cheers

**Comment by maxw** [comment]
Ok cool. That's what I was planning to do. Thanks for the quick response!

What do you mean by stream.GetAllocator()? As in use the steam's allocator to create a buffer based on the length when deserializing the message? I was planning to do something similar to "serialize_string_internal"

**Comment by gafferongames** [comment]
Yes exactly, my point is that you have the option of using the stream allocator on serialize read to dynamically allocate a buffer for your message, if that's helpful. -- cheers

**Comment by gafferongames** [comment]
Also, I think it makes sense for yojimbo to check the block message and if it fits inside an entire packet, to just send it quickly. I'll add that as a feature request. -- cheers

**Comment by maxw** [comment]
Ok perfect. One last question. Where is the best place to read the maximum size I can serialize in a non-block message? The "8 * 1024" value is stored in a config object that's private. I assume that yojimbo also adds a header to the packet that eats into this.

**Comment by maxw** [comment]
Wonderful!

**Comment by gafferongames** [comment]
Ahhhh. What you can do is setup your own "context" and pass that in to client and server configs, this is struct that can have whatever data you wish, shared between client and server. In here I think you should put your maximum message size. This way it can be threadsafe for future changes to the API...

**Comment by gafferongames** [comment]
As for what I would recommend for maximum size for non-block message, I would say that you should senda  block message if the size of the message is > 1/4 of your packet size, roughly, because it would stall out sends/receives anyway.

cheers

- glenn

**Comment by maxw** [comment]
Awesome. Thanks again! <3 yojimbo

**Comment by maxw** [comment]
In reference to this comment: https://github.com/networkprotocol/yojimbo/issues/71#issuecomment-339722055

I'd be down to implement this and submit a pull request. Is there a specific way you'd like me to go about implementing it?

**Comment by gafferongames** [comment]
I have no strong implementation feelings, as long as it is not visible to the user, eg. it is a "fake" message type or some internal fix to the reliable channel only. Also, I would like there to be a unit test added that reproduces this problem, and then demonstrates it fixed.

Thanks!

- Glenn

**Comment by gafferongames** [comment]
After this thread I had a crack at implementing this last year. I found that it was actually quite hard and I think I gave up. I'd be interested in seeing what your implementation is and would be happy to give feedback. -- cheers

**Comment by maxw** [comment]
I've spent some time digging into this. The best approach I can think of is to make IsBlockMessage() return false if the size of the block fits within a single packet. For small messages BlockMessage will handle serialization itself as if it's a normal message.

What do you think?

Max

**Comment by maxw** [comment]
Another somewhat related question is about unreliable channels. I want to build a solution that handles block messages that are too large for a single packet (I'm ok splitting them up, and discarding all chunks if one of them gets destroyed). In looking into this, I can't tell if yojimbo handles this automatically or not.

`Unreliable-unordered channels send blocks as-is without splitting them up into fragments. The idea is that transport level packet fragmentation should be used on top of the generated packet to split it up into into smaller packets that can be sent across typical Internet MTU (<1500 bytes).  Because of this, you need to make sure that the maximum block size for an unreliable-unordered channel fits within the maximum packet size.`

This makes me think that the packet will be broken up into <1500 chunks by the networking hardware? It also says the max block size must be less than the maximum packet size, however the default maxBlockSize is 256 * 1024 and the default maxPacketSize is 8 * 1024.

What am I missing?

Max
