### ISSUE TITLE
编译通不过

### ISSUE THREAD

**Issue by topxuchenghua** [networkprotocol/yojimbo#72]
![image](https://user-images.githubusercontent.com/15771965/32089090-8628d99a-bb1a-11e7-9273-782b6e69992c.png)

**Comment by gafferongames** [comment]
This looks extremely strange. What is the repro for this?

**Comment by topxuchenghua** [comment]
我看了只有后一个分支master分支啊，也拉最新。
![image](https://user-images.githubusercontent.com/15771965/32092601-d7a089a6-bb2b-11e7-9498-eb593f41b50c.png)
，然后再从 再拉netcode.io、reliable.io，代码放在目录编译，还是报错。

**Comment by gafferongames** [comment]
git submodule update --init
