### ISSUE TITLE
Token failed to decrypt

### ISSUE THREAD

**Issue by Zika01** [networkprotocol/yojimbo#73]
I ran into a snag trying to make the project work with Unity.
I got as far as getting a connection token from the "web backend" only for my connection request to time out.

We used the matcher to generate the token but when we attempt to connect using it the server outputs the following message:
"ignored connection request packet. connect token failed to decrypt"

**Comment by gafferongames** [comment]
Sounds like the connect token failed to decrypt!

**Comment by gafferongames** [comment]
(Typically when the connect token fails to decrypt, it means the connect token was encrypted with a different private key than the server has. Check your private keys :))
