### ISSUE TITLE
Unreliable-Sequenced with Acknowledgement Channel

### ISSUE THREAD

**Issue by Aloshi** [networkprotocol/yojimbo#74]
Hello, I'm interested in using yojimbo with an unreliable-sequenced stream of object updates with acknowledgements for which messages are actually received by the client. (Something like the `UNRELIABLE_SEQUENCED_WITH_ACK_RECEIPT` message type from [RakNet](http://www.jenkinssoftware.com/raknet/manual/reliabilitytypes.html).)

I've looked through the code, and this seems pretty hard to implement since all channels are multiplexed into one packet with one sequence number. I can easily do sequencing on the client, but I don't think I can use the current system (`Channel::onAck`) to detect ignored out-of-order packets on the server - there's the possibility of out-of-order acks sent by the client becoming in-order on the way to the server. If I skip sending acks from the client for out-of-order packets, I'd cause unnecessary strain on any reliable channels.

Just curious about your thoughts. If there's a reasonably easy way to do it, I might give implementing it into the library proper a shot. If not, I can just do the sequencing manually inside my messages.

Thanks for the library, good luck with the startup!

**Comment by gafferongames** [comment]
I recommend sequencing manually inside your messages.
