### ISSUE TITLE
Client timeouts as server tries to keep up with incoming packets

### ISSUE THREAD

**Issue by maxw** [networkprotocol/yojimbo#76]
My client & server both run at 90hz and are currently running on the same windows machine. In my current setup, my client sends two unreliable messages each network frame.

I have a reliable test message that can be sent from the client that causes the server to print a log. As the session advances, the latency between when this message is sent and when the server prints the log increases until the client doesn't receive a response fast enough, times out, and then disconnects.

My server right now doesn't do anything with the messages except examine the message type and release it. I imagine that packets are building up somewhere, but I can't tell if it's because I'm sending too much data, or if I'm possibly calling SendPackets() too often and so the small messages aren't getting grouped together into a single packet.

Is there a recommended way to debug this problem?

Max

**Comment by gafferongames** [comment]
Are you sending and receiving packets in both directions continuously? That's required for correct yojimbo operation.

Also, to debug, set yojimbo_log_level( YOJIMBO_LOG_LEVEL_DEBUG ) on both client and server and attach the logs to this thread.

cheers

**Comment by maxw** [comment]
I am sending two packets at 90hz continuously in both directions. After digging some more, it seems I was sending too much data (over 200kb/s). I brought one of the larger packets down to 20hz which has fixed all of the slow-down issues I was having. I'll close this issue.

It's looking like I'll need to implement my own fragmentation for large unreliable packets (over the max packet size). I'd love an easy way to measure bandwidth, and whether packets are being filled up completely when yojimbo finishes filling a packet with messages.

Max
