### ISSUE TITLE
Serialize connection packet failed between Linux server and Linux client

### ISSUE THREAD

**Issue by jarrettchisholm** [networkprotocol/yojimbo#77]
Hello,

I was working to integrate your library into a game engine, and have come across a weird issue. 

I have slightly modified the `server.cpp`, `client.cpp`, and `shared.h` files in order to reproduce.

When I run the server and client in Linux, I get the following error:

```
started server on port 40000 (insecure)
server listening on 127.0.0.1:40000
server started with 64 client slots
server address is 127.0.0.1:40000
server accepted client 127.0.0.1:42016 0e4caff7cf34d61f in slot 0
server received message 0
error: failed to serialize channel 0
error: serialize connection packet failed (read packet)
error: failed to read packet
[server endpoint] process packet failed
client 4 connection is in error state. disconnecting client
server disconnected client 0
```

When I run the server in Linux and client in Windows, I get the following error:

```
started server on port 40000 (insecure)
server listening on 127.0.0.1:40000
server started with 64 client slots
server address is 127.0.0.1:40000
server accepted client 10.0.2.2:50767 9125a20b5e2f7387 in slot 0
error: serialize check failed at end of connection packet (read packet)
error: failed to read packet
[server endpoint] process packet failed
client 4 connection is in error state. disconnecting client
server disconnected client 0
```

If I run the client and the server on the Windows machine, I get no problems.

It seems that the issue occurs when I only have one type of message registered. If I register a second message type, I no longer get this error.

I am running Windows 10 64-bit and I'm using Visual Studio 2017 to compile.
My Linux machine is Linux 4.4.0-104-generic #127-Ubuntu SMP Mon Dec 11 12:16:42 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux. I am using gcc version 6.3.0 20170519 (Ubuntu/Linaro 6.3.0-18ubuntu2~16.04). The Linux machine is within a VirtualBox VM.

Do you have any ideas what might be causing this issue?

[files.zip](https://github.com/networkprotocol/yojimbo/files/1610103/files.zip)

**Comment by gafferongames** [comment]
OK cool. I think I might know what is going on. There is special code to handle the "broken case" of just one message type, but maybe that is not working across the two platforms. It should though. 

For the moment, please workaround by having 2 or more message types registered.

thanks.

**Comment by gafferongames** [comment]
ps. I'll bet it's some uninitialized data thing... which would explain the behavior being different across different OS/compiler combos.

**Comment by gafferongames** [comment]
We could use some help investigating and fixing. My guess is uninitialized data, something to do with the message type serialization. Might be a bug in the serialize method, but in such a way that it only manifests on one platform, and not the other, or one compiler...
