### ISSUE TITLE
Thread safety

### ISSUE THREAD

**Issue by yamashi** [networkprotocol/yojimbo#80]
Hello,

We are getting occasional crashes in tlsf_free, I am guessing this is caused by thread safety issues, was yojimbo designed thread-safe or should we add our own wrappers ?

https://cdn.discordapp.com/attachments/380142386057314304/416355668971225088/unknown.png

Thanks,
Max

**Comment by gafferongames** [comment]
You should add your own wrappers.

- Glenn
