### ISSUE TITLE
round trip time slowly increases?

### ISSUE THREAD

**Issue by maxw** [networkprotocol/yojimbo#82]
If you checkout a fresh copy of yojimbo and add the following to the end of the while() loop in the loopback.cpp example, you'll see the round trip time value increases slowly (screenshot attached)

```
NetworkInfo networkInfo;
client.GetNetworkInfo(networkInfo);
printf("RTT: %f\n", networkInfo.RTT);
```

![rtt](https://user-images.githubusercontent.com/396729/38447887-6073bcbe-39ce-11e8-966c-1107f65deb0d.png)

(This is running on windows btw)

Max

**Comment by maxw** [comment]
Also worth mentioning that by "fresh copy", I mean yojimbo master w/o the latest commit that updates submodules because the latest versions of netcode.io and reliable.io break yojimbo.

**Comment by gafferongames** [comment]
Yeah I gotta fix that 

- Glenn

**Comment by maxw** [comment]
So the client_server.cpp sample seems to remain constant, but it sticks at 600ms with the default deltaUpdate time of 100ms. Any idea what's up with that? I'd expect 100 or 200ms, but not 600ms.

Max

**Comment by maxw** [comment]
Worth mentioning that I'm trying to write some code that will give me a timestamp on all clients that's roughly in sync with the server. My plan was to have the server send its timestamp on connect, then subtract half of the roundtrip time from that.

**Comment by gafferongames** [comment]
Weird

- Glenn

**Comment by maxw** [comment]
I'll keep digging... Let me know if you think of what could be wrong. I'll make a fix and submit a PR.

Max

**Comment by gafferongames** [comment]
I'm not sure the above is correct. The acks *should* be measuring actual network latency from a client to the server and back, it's difficult to see how the client_server.cpp loopback test should have an effective latency of 600ms, so my bet is that the RTT calculation is broken.

I guess I should take a look this weekend.

**Comment by gafferongames** [comment]
> reliable.io sends a packet with a timestamp, the server sends this timestamp back in the corresponding ack, and then the client compares how old the timestamp is to its current clock. However, since acks are so heavily delayed, the round trip time calculation is always off.

It doesn't actually work this way. No timestamp is sent over the network by reliable.io, only sequence numbers. The client stores its local sequence # per-timestamp at time of send, and compares with the timestamp when received, and that is what it considers the RTT to be.

Are you saying that the server is basically acking blocks of packets, so in your case, it's getting an ack for the old n frames as well as the most recent feeding in and causing this? That sounds like the most likely culprit to me, and fixing that should be easy, eg. only do RTT calculation on the most recent ack in a packet...

**Comment by maxw** [comment]
Even if the timestamp is cached locally, the issue is that the sequence numbers in each ack are delayed. When the server receives sequence 0, the ack 0 message doesn't go out in the same or even next SendPackets()/ReceivePackets() loop.

If you turn on debug logging in the client_server example and add a log at the beginning/end of the while loop, you'll see something like this: (I've stripped some of the excess messages)

```
[client/server]
started server
client started on port 53847
client connecting to server 127.0.0.1:40000 [1/1]

Run loop began begin
client sent connection request packet to server
server received connection request from 127.0.0.1:53847
server sent connection challenge packet
Run loop ended. Current RTT: 0.000000

Run loop began begin
client received connection challenge packet from server
client sent connection response packet to server
server accepted client 127.0.0.1:53847 b2894f3ebf089be5 in slot 0
Run loop ended. Current RTT: 0.000000

Run loop began begin // Packet 0 goes out here
[server endpoint] sending packet 0 without fragmentation
[client endpoint] sending packet 0 without fragmentation
client connected to server
Run loop ended. Current RTT: 0.000000

Run loop began begin
[server endpoint] sending packet 1 without fragmentation
[client endpoint] sending packet 1 without fragmentation
[client endpoint] processing packet 0
[client endpoint] process packet 0 successful
Run loop ended. Current RTT: 0.000000

Run loop began begin
[server endpoint] sending packet 2 without fragmentation
[client endpoint] sending packet 2 without fragmentation
[server endpoint] processing packet 1
[server endpoint] process packet 1 successful
[client endpoint] processing packet 1
[client endpoint] process packet 1 successful
Run loop ended. Current RTT: 0.000000

Run loop began begin // Ack 0 is received here
[server endpoint] sending packet 3 without fragmentation
[client endpoint] sending packet 3 without fragmentation
[server endpoint] processing packet 2
[server endpoint] process packet 2 successful
[server endpoint] acked packet 0
 // This is my own log that prints the RTT for a single packet right when it arrives (instead of the average)
Received Packet! RTT: 600 - current endpoint time: 101.000000 - packet time:100.400000
[client endpoint] processing packet 2
[client endpoint] process packet 2 successful
Run loop ended. Current RTT: 0.000000

Run loop began begin
[server endpoint] sending packet 4
[server endpoint] sending packet 4 without fragmentation
[client endpoint] sending packet 4
[client endpoint] sending packet 4 without fragmentation
[server endpoint] processing packet 3
[server endpoint] process packet 3 successful
[server endpoint] acked packet 1
packet rtt: 0.600000 - endpoint time: 101.200000 - packet time:100.600000
[client endpoint] processing packet 3
[client endpoint] process packet 3 successful
[client endpoint] acked packet 1
packet rtt: 0.600000 - endpoint time: 101.100000 - packet time:100.500000
Run loop ended. Current RTT: 600.000000
```

**Comment by maxw** [comment]
One other note for clarity: the client_server example still connects over local sockets instead of using the loopback APIs in yojimbo. The loopback example has its own problems with growing RTT time. 

client_server stays constant, but the RTT calculation is much larger than your ping + deltaTime would be due to acks going out several send/receive loops later.

**Comment by gafferongames** [comment]
Seems like a bug.

**Comment by maxw** [comment]
Let me know if you think of what might be causing it. I keep looking into how reliable.io does its acks and haven't come up with anything.

**Comment by gafferongames** [comment]
I suspect the bug is on the yojimbo side, *or* it's something super dumb in
my rtt calculations. reliable.io maybe... but it's such a simple system...

**Comment by maxw** [comment]
I can confirm that when [reliable.io does the rtt calculation for a single packet](https://github.com/networkprotocol/reliable.io/blob/master/reliable.c#L1109), it comes back incorrectly, which rules out the math that does the averaging in yojimbo. And the calculation in reliable is just (send_time - current_time), so I don't think the math is wrong.

It's definitely due to these ack messages coming in several Send/Receive loops later. And from the looks of it reliable.io is responsible for deciding when these acks are sent out.

**Comment by maxw** [comment]
I've been working on another bug and found that the delayed acks actually cause yojimbo to send most reliable messages multiple times too.

If you add this line to the Serialize template on TestMessage you can see it in action:
`yojimbo_printf(YOJIMBO_LOG_LEVEL_INFO, "Serialize test message (ReadStream: %i, MeasureStream: %i, WriteStream: %i)", std::is_same<Stream, Yojimbo::ReadStream>::value, std::is_same<Stream, Yojimbo::MeasureStream>::value, std::is_same<Stream, Yojimbo::WriteStream>::value);`

You'll get logs similar to this for all clients that have a ping time above 15ms:
`
Log: SendMessage(TestMessage)
Log: Serialize test message (ReadStream: 0, MeasureStream: 1, WriteStream: 0)
Log: Serialize test message (ReadStream: 0, MeasureStream: 0, WriteStream: 1)
Log: Serialize test message (ReadStream: 0, MeasureStream: 0, WriteStream: 1)
Log: Serialize test message (ReadStream: 0, MeasureStream: 0, WriteStream: 1)
`

I have a production app that uses yojimbo. I see this behavior for all reliable messages that we send to clients with a ping time above 15ms.

I haven't dug too much more, but I imagine this also means yojimbo uses about 3x the bandwidth when sending reliable messages. I'm still deep on another bug, but will let you know when I get more time to look into this one.

Max

**Comment by gafferongames** [comment]
That makes sense. Yojimbo is currently setup to resend unacked reliable
messages every 10th of a second.

You can change this in the reliable channel config to make it resend
unacked messages less frequently.

**Comment by maxw** [comment]
Now that I think about it, every 10th of a second would be 100ms. I'm seeing this bug with people who have a ping <50ms and with our server running with a run loop time of 10ms. The default message resend time seems ideal for us, but because round trip times are 600ms even when both client/server are running on the same machine, every reliable message fails the message resend time test.

**Comment by gafferongames** [comment]
This sounds crazy. Why isn't everybody else seeing this behavior?

**Comment by maxw** [comment]
I imagine they are seeing this behavior... That said, resending packets has no noticeable effect on anything other than bandwidth usage, so I doubt anyone has noticed. And given that the bandwidth stats are averaged over a few seconds, unless someone is sending a constant stream of reliable updates, this bug wouldn't be apparent in those stats either.

**Comment by maxw** [comment]
I think most people assume that if things are getting through, the system is working perfectly.

**Comment by gafferongames** [comment]
Maybe we should do a consult. I'm happy to look into this specific bug for
you, and it probably won't take a lot of time, but I have to prioritize
paid work for my company first.

Would you like me to look into this as paid work? I'm sure it would only
take a few hours.

cheers

- Glenn

**Comment by maxw** [comment]
No worries. I'm not in a huge rush over here. I'll add it to my list and fix it down the road.

Apologies if these bug reports are getting annoying btw. I figured it would be helpful to write up my findings as I go in case anything stuck out to you. Happy to keep quiet until I have PRs ready for each bug that I find.

Max

**Comment by gafferongames** [comment]
Not annoying. Just don't have a lot of time to investigate right now.

cheers

- Glenn

**Comment by PlasmaMichael** [comment]
I also have a server and client on the same computer running and with the app at 60FPS, I have around 70ms as RTT. I would expect 16ms to 33ms... Any thought ?

**Comment by maxw** [comment]
Last I looked into this, it's caused by reliable.io resending all reliable packets three times. Unfortunately, I didn't have time to dig into the root cause and had to write my own rtt calculation.

**Comment by gafferongames** [comment]
Friends, it seems like there is a bug here. RTT should work properly. I'm super slammed with my new startup, but it would be great if somebody could investigate this, and then we could get a new release out with all the fixes!

Thanks

**Comment by erdinckaya** [comment]
@gafferongames @maxw I am really new at yojimbo but I tried your problem on my local machine on mac. With loopback.cpp example it gives exactly your output but I think that example is wrong because it is advancing the client time before server. If we cut the `client.AdvanceTime( time );`  and paste it after `server.AdvanceTime( time );` it works properly and gives 200ms always. I tried it with secure server and secure clients, it works normal with delta_time 0.1 it gives 200 with delta_time 1/60 it gives 33.891ms. As I said before I am really new in yojimbo and my bold assumption is check `client.AdvanceTime( time );` for rtt problem. I think it is important for calculating RTT. I hope it helps you.

**Comment by gafferongames** [comment]
Yes, you need client.AdvanceTime!

**Comment by maxw** [comment]
This fixes the loopback client, but does it fix the client_server example for you? For my most recent tests, I was running client / server in separate processes on the same machine...

**Comment by erdinckaya** [comment]
Hi @maxw let me show you examples. In the usage.md file there is a paragraph about that.
`In the Update method, there are 3 methods of the Server class that you need to call: AdvanceTime, ReceivePackets and SendPackets. Note that the order is very important. Using another order might add a couple frames of delay to your server's latency. Here is what it looks like:`

I think this paragraph is valid for client loop too.

`
void GameServer::Update(float dt) {
    // stop if server is not running
    if (!m_server.IsRunning()) {
        m_running = false;
        return;
    }

    // update server and process messages
    m_server.AdvanceTime(m_time);
    m_server.ReceivePackets();
    ProcessMessages();

    // ... process client inputs ...
    // ... update game ...
    // ... send game state to clients ...

    m_server.SendPackets();
}
`


And there is my server.cpp
`
#include "pch.h"
#include "yojimbo.h"
#include <signal.h>
#include <time.h>

#include "shared.h"


using namespace yojimbo;

static volatile int quit = 0;

void interrupt_handler(int /*dummy*/)
{
	quit = 1;
}

int ServerMain()
{
	printf("started server on port %d (insecure)\n", ServerPort);

	double time = 0;

	ClientServerConfig config;

	uint8_t privateKey[KeyBytes];
	memset(privateKey, 0, KeyBytes);

	Server server(GetDefaultAllocator(), privateKey, Address("127.0.0.1", ServerPort), config, adapter, time);

	server.Start(MaxClients);

	char addressString[256];
	// ReSharper disable once CppExpressionWithoutSideEffects
	server.GetAddress().ToString(addressString, sizeof(addressString));
	printf("server address is %s\n", addressString);

	const double deltaTime = 0.1;

	signal(SIGINT, interrupt_handler);


	while (!quit)
	{
		server.AdvanceTime(time);
		server.ReceivePackets();



		server.SendPackets();

		time += deltaTime;

		

		if (!server.IsRunning())
			break;

		yojimbo_sleep(deltaTime);
	}

	server.Stop();

	return 0;
}

int main()
{
	printf("\n");

	if (!InitializeYojimbo())
	{
		printf("error: failed to initialize Yojimbo!\n");
		return 1;
	}

	yojimbo_log_level(YOJIMBO_LOG_LEVEL_INFO);

	srand((unsigned int)time(NULL));

	int result = ServerMain();

	ShutdownYojimbo();

	printf("\n");

	return result;
}`

Client.cpp

`#include "pch.h"
#include "yojimbo.h"
#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
#include <inttypes.h>
#include <time.h>
#include <signal.h>
#include "shared.h"

using namespace yojimbo;

static volatile int quit = 0;

void interrupt_handler(int /*dummy*/)
{
	quit = 1;
}

int ClientMain(int argc, char* argv[])
{
	printf("\nconnecting client (insecure)\n");

	double time = 0;

	uint64_t clientId = 0;
	random_bytes((uint8_t*)&clientId, 8);
	printf("client id is %.16" PRIx64 "\n", clientId);

	ClientServerConfig config;

	Client client(GetDefaultAllocator(), Address("0.0.0.0"), config, adapter, time);

	Address serverAddress("127.0.0.1", ServerPort);

	if (argc == 2)
	{
		Address commandLineAddress(argv[1]);
		if (commandLineAddress.IsValid())
		{
			if (commandLineAddress.GetPort() == 0)
				commandLineAddress.SetPort(ServerPort);
			serverAddress = commandLineAddress;
		}
	}

	uint8_t privateKey[KeyBytes];
	memset(privateKey, 0, KeyBytes);

	client.InsecureConnect(privateKey, clientId, serverAddress);

	char addressString[256];
	// ReSharper disable once CppExpressionWithoutSideEffects
	client.GetAddress().ToString(addressString, sizeof(addressString));
	printf("client address is %s\n", addressString);

	const double deltaTime = 0.1;

	signal(SIGINT, interrupt_handler);

	while (!quit)
	{

		client.AdvanceTime(time);
		client.ReceivePackets();


		NetworkInfo network_info;
		client.GetNetworkInfo(network_info);
		printf("RTT is %f\n", network_info.RTT);
		

		client.SendPackets();
		time += deltaTime;

		if (client.IsDisconnected())
			break;

		


		if (client.ConnectionFailed())
			break;

		yojimbo_sleep(deltaTime);
	}

	client.Disconnect();

	return 0;
}

int main(int argc, char* argv[])
{
	if (!InitializeYojimbo())
	{
		printf("error: failed to initialize Yojimbo!\n");
		return 1;
	}

	yojimbo_log_level(YOJIMBO_LOG_LEVEL_INFO);

	srand((unsigned int)time(NULL));

	int result = ClientMain(argc, argv);

	ShutdownYojimbo();

	printf("\n");

	return result;
}
`

I tested this in Windows 10 machine and my results are changing between 100  - 103 ms on mac it is almost stable 100ms.

![rtt](https://user-images.githubusercontent.com/7902646/46905549-1ab6c200-cefe-11e8-9d53-2c5566b21d41.PNG)

I think results are pretty acceptable. I am gonna create a tutorial about creating secure server and secure client aswell -If I can found time I am gonna make video too-. When I finish it I can share with you guys
