### ISSUE TITLE
Lan Host search

### ISSUE THREAD

**Issue by gdlk1** [networkprotocol/yojimbo#88]
Hi!
I am learning to use the library and I am stuck trying to create a host search mechanism for LAN (a player create a room like a server, then other players can join to it). In my old code I use a broadcast to search in the LAN if someone create a server, however I am not sure how to do that in this library.

There is some example code about that? or, if it is not implemented, could you give a tip about where implement the mechanism in the library?

Regards!

**Comment by gafferongames** [comment]
There is no LAN search provided by the library, but you could easily implement your own, and once you know the IP address of the server to connect to, just connect with yojimbo.

Alternatively, a more modern way is to implement your own matchmaker.

See matcher.go

cheers
