### ISSUE TITLE
ignored connection request packet. connect token expired

### ISSUE THREAD

**Issue by gdlk1** [networkprotocol/yojimbo#90]
Hi, 

I am trying to connect a client to a server in a LAN network with yojimbo::client::InsecureConnect method. 

With two pc (A and B), when I try to connect from A to B, always works fine, however when I try to connect from B to A, I only get "ignored connection request packet. connect token expired" in A.

The code to reproduce is attached (in the begin of main.cpp, just change the variable ipToConnect to set the host ip (in client and server code). In the server code comment the line 219 (connectToServer()) )

Any idea what could be?

Regards!

Another hints: If use the debug mode in the server, set a breakpoint anywhere to stop the run after the ignore connection message shows, then remove breakpoint and resume the run, the connection works

[testIssueYojimbo.zip](https://github.com/networkprotocol/yojimbo/files/2051751/testIssueYojimbo.zip)

**Comment by gafferongames** [comment]
Check that the two machines both have synchronized clocks. They are probably slightly out of sync. The connect token has a timestamp in it that is used to determine expiry.
