### ISSUE TITLE
Messages being silently removed when going beyond the size limits

### ISSUE THREAD

**Issue by BillEnvrmnt** [networkprotocol/yojimbo#92]
Hi! I've run into an issue where depending on the amount of messages I attempt to send in a single frame some are silently deleted and not sent by Yojimbo. Digging into it a bit I've found that UnreliableUnorderedChannel does this within its 'GetPacketData' function here:
```
            if ( usedBits + messageBits > availableBits )
            {
                m_messageFactory->ReleaseMessage( message );
                continue;
            }
```
Naturally this check is totally valid but I don't see an easy way to determine how much space left I have within a given channel for additional messages. I've found the 'CanSendMessage' function but that checks the number of messages, not the total size of them.

Is there a way to determine how much space is left for a given channel or more directly to see if a given Message instance will fit within a given channel? If not would it be possible to add API to query such a thing?

**Comment by gafferongames** [comment]
Generally, it's not possible to know ahead of time, since the messages can be of variable size.

I recommend setting increasing your reliable channel budget, and enforcing a limit based on the # of messages. It's the simplest approach.

cheers

**Comment by gafferongames** [comment]
Also, please look into the "MeasureStream" examples in the unit tests. You may be able to use that conservatively measure your events, add some slop (header, and per-event), and knowing an upper bound for the total size of your serialized messages.

**Comment by gafferongames** [comment]
You can even find some code that does this inside the reliable channel, since it has to enforce budgets, you could probably hack copy some of that code out, get an approximation for max size of messages sent this frame so far, and get what you need.
