### ISSUE TITLE
Connection from another computer

### ISSUE THREAD

**Issue by PlasmaMichael** [networkprotocol/yojimbo#94]
Hi,
After experimenting long time it looks like the only way to connect from another computer is to add "0.0.0.0" with the server port in the addresses of the client insecure connect function. The server has the address "0.0.0.0" with the same port. The client has the address 0.0.0.0 without a port set. I don't have it working with the internet ip, only lan connection works.
Is it possible to have the answer on how to have it working in all situations correctly ?
Another question about the same topic is : is it possible to get the internet ip from the API ?
Thank you

**Comment by gafferongames** [comment]
You have to put the actual public IP address in when you are connecting to another computer.

**Comment by gafferongames** [comment]
(Don't start the server with 0.0.0.0 bind, start it with the actual public IP address...)

**Comment by PlasmaMichael** [comment]
There is no way to know the actual public IP to set this on a text edit widget ? There is 2 IP, LAN and Internet, maybe possible to have the both ? Something missing in Yojimbo and need to be implemented aside ?

**Comment by PlasmaMichael** [comment]
For LAN the server has to put his LAN address and the client his LAN address and connect insecure with the server LAN address with the good port ?

For Internet, same process ? Put the Internet IP on server and client and connect insecure with the Internet IP with the good port ?

If all that is yes then it's certainly a blocked port issue...

Another question is:
Is it important to specify a port for the client IP ?

Thank you for the help :)

**Comment by RickLamb** [comment]
It's not possible to automatically determine your public internet IP, between NAT and VPN and such it just isn't a question with a simple answer a lot of the time. The server needs to be told the connection address and port to use, and the client needs to be told the same connection address and port. Client often via a matchmaker, server by whatever is launching server via cmd line normally.

**Comment by gafferongames** [comment]
You need to host a dedicated server with a public IP address, for example linode.com

Then when you start the server, you specify the public IP address on the server.

Then the client connects to the public ip address of the server.

(Ideally, you don't connect insecure, instead, you have a matchmaker that holds the private key and creates the connect token, you don't want clients to have the private key...)

cheers
