### ISSUE TITLE
basic how to: connection issues when sending messages repeatedly in a gameloop (2D position of an object)

### ISSUE THREAD

**Issue by ChristianHohlfeld** [networkprotocol/yojimbo#99]
Hi, I'm trying to send position information (x and y) from client to server. It happens that I loose the connection or the number of connections reported by the server is 0 even though the client sends connection requests. I'm sending at a rate of 800ms and get the following debug output from yojimbo. 
Yojimbo server log:
https://gist.github.com/ChristianHohlfeld/89447b722789c39e3379442e53de2946

The client gets initialised like that:
https://gist.github.com/ChristianHohlfeld/37a3071d30cced4af8ddd9613813dad1

The server initialisation:
https://gist.github.com/ChristianHohlfeld/1da9cad8a09c79cd4cbaa2c349490b5c

GameMessageFactory.h:
https://gist.github.com/ChristianHohlfeld/c83ffc97347dc12781329ccbcc024785

GameAdapter.h
https://gist.github.com/ChristianHohlfeld/cdc877dda059683e0e1b70955219f2ce
GameAdapter.cpp
https://gist.github.com/ChristianHohlfeld/fdaf011d7a37a207da02d050eeb9ae97

Server update:
https://gist.github.com/ChristianHohlfeld/71376b1f67ff75a09f8d81d97fb1f792

Client Update:
https://gist.github.com/ChristianHohlfeld/f92a8dd91baf4582f694bcd41cea252c

The Method where the Message gets sent:
https://gist.github.com/ChristianHohlfeld/968e221cee874242bc0c2e6636693d26

The game loop looks like this:
https://gist.github.com/ChristianHohlfeld/22a2046c150b0975ada3d0695782a6b7

Message.h:
https://gist.github.com/ChristianHohlfeld/c671eb8753d19660b861a593c5d679a3

GameServer.h:
https://gist.github.com/ChristianHohlfeld/4d71f9e46288a7206fbc7f032c175a66
GameServer.cpp:
https://gist.github.com/ChristianHohlfeld/dea566f451c3f720a76ca7527f60fd74

GameClient.h:
https://gist.github.com/ChristianHohlfeld/7e6e205cc4e6a3fce25a3b51bcc019c0
GameClient.cpp:
https://gist.github.com/ChristianHohlfeld/745de6e7541638eeb1d5fecc7fe66ecc

Physics.h (fixed timestamp and interpolation of sprite positions):
https://gist.github.com/ChristianHohlfeld/3ce7e4649e269c6d18fab4b5cff47084
Physics.cpp:
https://gist.github.com/ChristianHohlfeld/bdf2b75f31d246f30d1539ce41208e8b
( from http://plaincode.blogspot.com/2012/05/fixed-timestep-in-cocos2d-x-with-box2d.html )

Any help appreciated, thank you!

**Comment by gafferongames** [comment]
Can you create a minimal, stand-alone repro that allows me to debug this issue?

**Comment by ChristianHohlfeld** [comment]
I will. Thanks for your time!

**Comment by ChristianHohlfeld** [comment]
I created an example project that shows how I integrated yojimbo inside cocos2d-x. I'm not quite there to reproduce the errors yet but I think it will be done within the next few days. For now you can take a look at my posts which describes the process [www.ragdoll-tv.de](url) if you like. Thanks for your time.

**Comment by ChristianHohlfeld** [comment]
Please close this issue, it works now and I couldn't reproduce the issue mentioned before. Thank you!
